.type ID
.type Pid
.type Name
.type G

.decl Rule(n: number)
.input Rule

.decl In(v0: ID, v1: Pid, v2: Name, v3: G)
.input In
.decl Lt(v0: G, v1: G)
.input Lt

.decl invent_1(v0: Pid, v1: G)
.output invent_1
.decl Out(v0: Pid, v1: G, v2: G)
.output Out

Out(v3, v4, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v4, v2), Rule(225).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v3), Rule(92).
Out(v4, v0, v3) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v0), Rule(466).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v0, v2), Rule(296).
invent_1(v0, v4) :- Out(v0, v1, v2), Out(v0, v2, v3), Lt(v3, v4), Rule(372).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v1, v0), In(v2, v3, v4, v1), Rule(627).
invent_1(v0, v5) :- Out(v0, v1, v2), Out(v3, v1, v4), Out(v0, v4, v5), Rule(527).
Out(v0, v3, v2) :- Out(v0, v1, v2), invent_1(v0, v1), Lt(v2, v3), Rule(575).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(445).
Out(v2, v0, v5) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v3, v5), Rule(99).
Out(v2, v1, v0) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v0), Rule(115).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v5, v0), Rule(634).
Out(v2, v3, v4) :- Lt(v0, v1), Out(v2, v0, v3), Out(v2, v1, v4), Rule(104).
Out(v4, v3, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(469).
Out(v3, v2, v4) :- Out(v0, v1, v2), invent_1(v3, v1), invent_1(v3, v4), Rule(328).
Out(v2, v4, v0) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v4), Rule(401).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v3, v4), invent_1(v2, v0), Rule(637).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v2, v3), Rule(146).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v1), Rule(636).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v5), Rule(18).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v1, v3), Rule(329).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v1), invent_1(v2, v3), Rule(502).
Out(v2, v1, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(74).
invent_1(v0, v1) :- Out(v0, v1, v2), invent_1(v3, v1), invent_1(v0, v4), Rule(52).
Out(v2, v4, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v3, v4), Rule(560).
invent_1(v0, v3) :- Out(v0, v1, v2), invent_1(v0, v1), Lt(v1, v3), Rule(288).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v4), Rule(38).
Out(v4, v3, v0) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v0, v3), Rule(402).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v0), Out(v3, v4, v1), Rule(607).
Out(v2, v1, v0) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v2, v0), Rule(543).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v0, v2), Out(v3, v0, v2), Rule(508).
invent_1(v0, v4) :- Out(v0, v1, v2), invent_1(v3, v1), invent_1(v3, v4), Rule(200).
invent_1(v2, v3) :- Lt(v0, v1), invent_1(v2, v1), Out(v2, v3, v0), Rule(236).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v0), Rule(125).
Out(v2, v3, v0) :- Lt(v0, v1), Out(v2, v1, v0), invent_1(v2, v3), Rule(240).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v1, v3), Rule(319).
invent_1(v0, v2) :- invent_1(v0, v1), Out(v0, v2, v1), Lt(v3, v2), Rule(671).
invent_1(v5, v3) :- In(v0, v1, v2, v3), Lt(v4, v3), invent_1(v5, v4), Rule(498).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v0, v2), Out(v3, v2, v1), Rule(169).
Out(v2, v0, v3) :- Lt(v0, v1), Lt(v1, v0), Out(v2, v3, v1), Rule(617).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v3), Rule(190).
Out(v2, v1, v3) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v3, v4), Rule(367).
Out(v2, v1, v0) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v1), Rule(676).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v1, v3), Rule(479).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v4, v2), Rule(257).
Out(v4, v3, v1) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v3, v0), Rule(268).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v1), Rule(261).
Out(v3, v1, v4) :- Out(v0, v1, v2), invent_1(v3, v4), invent_1(v3, v1), Rule(339).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v3), Rule(622).
Out(v3, v1, v0) :- Lt(v0, v1), invent_1(v2, v0), invent_1(v3, v1), Rule(251).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v0), Rule(233).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v3), Rule(603).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v5, v3), Rule(643).
Out(v3, v4, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(566).
Out(v4, v0, v3) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v3), Rule(356).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v0, v3), Rule(247).
Out(v2, v3, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v3), Rule(541).
invent_1(v0, v3) :- Out(v0, v1, v1), Out(v2, v1, v3), invent_1(v0, v4), Rule(201).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(553).
Out(v2, v4, v0) :- Lt(v0, v1), Out(v2, v0, v3), Out(v2, v1, v4), Rule(509).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v3), Rule(37).
invent_1(v0, v2) :- invent_1(v0, v1), Out(v0, v2, v1), Lt(v2, v3), Rule(489).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v4, v2), Rule(467).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v0, v2), Out(v3, v0, v2), Rule(58).
invent_1(v0, v5) :- Out(v0, v1, v2), Out(v0, v1, v3), Out(v4, v3, v5), Rule(320).
invent_1(v4, v2) :- Out(v0, v1, v2), invent_1(v3, v2), invent_1(v4, v1), Rule(82).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v4, v2), Rule(369).
invent_1(v3, v2) :- Out(v0, v1, v2), Out(v3, v2, v1), invent_1(v3, v4), Rule(398).
Out(v2, v1, v4) :- Lt(v0, v1), Out(v2, v3, v0), Lt(v4, v3), Rule(297).
invent_1(v4, v3) :- Out(v0, v1, v2), Out(v0, v2, v3), invent_1(v4, v1), Rule(208).
invent_1(v0, v2) :- invent_1(v0, v1), Out(v0, v1, v2), invent_1(v3, v2), Rule(147).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v1), Rule(492).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v4), Rule(484).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v1), Rule(406).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v0, v1), Out(v3, v4, v0), Rule(180).
Out(v2, v3, v1) :- Lt(v0, v1), invent_1(v2, v0), invent_1(v2, v3), Rule(591).
Out(v4, v1, v2) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v0, v2), Rule(347).
Out(v2, v1, v4) :- Lt(v0, v1), Out(v2, v0, v3), Lt(v3, v4), Rule(56).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v1), Rule(20).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v1, v2), invent_1(v3, v2), Rule(572).
invent_1(v2, v5) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v5), Rule(195).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v1), invent_1(v3, v2), Rule(480).
Out(v4, v0, v3) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v5, v0), Rule(546).
Out(v3, v4, v2) :- Out(v0, v1, v2), invent_1(v3, v1), Out(v3, v2, v4), Rule(433).
invent_1(v0, v4) :- invent_1(v0, v1), Out(v0, v2, v1), Out(v3, v2, v4), Rule(371).
Out(v4, v1, v3) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v0, v3), Rule(586).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(663).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v0), invent_1(v3, v2), Rule(464).
Out(v2, v5, v3) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v5, v0), Rule(244).
Out(v3, v1, v2) :- invent_1(v0, v1), invent_1(v0, v2), invent_1(v3, v2), Rule(605).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v5), Rule(217).
Out(v4, v0, v3) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v1, v3), Rule(12).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v2, v4, v1), Rule(31).
Out(v2, v0, v4) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v4), Rule(407).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v0), invent_1(v2, v3), Rule(587).
invent_1(v3, v5) :- Out(v0, v1, v2), Out(v3, v4, v1), invent_1(v0, v5), Rule(614).
Out(v4, v1, v3) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v3, v0), Rule(365).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v1), Rule(532).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(439).
Out(v2, v4, v1) :- Lt(v0, v1), Out(v2, v0, v3), Lt(v3, v4), Rule(267).
Out(v3, v0, v4) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v4), Rule(164).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v3), Rule(54).
invent_1(v3, v2) :- Out(v0, v1, v2), invent_1(v3, v1), Out(v3, v2, v4), Rule(119).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v1, v3), Out(v2, v4, v0), Rule(243).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v1), Rule(85).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v3), Rule(264).
invent_1(v3, v0) :- Lt(v0, v1), invent_1(v2, v0), invent_1(v3, v1), Rule(274).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v0), Rule(373).
Out(v2, v0, v1) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v0), Rule(305).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v1), Rule(232).
Out(v2, v1, v0) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v1), Rule(668).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v4), Rule(126).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v1, v2), invent_1(v3, v2), Rule(163).
invent_1(v0, v4) :- Out(v0, v1, v2), Out(v0, v3, v1), Lt(v3, v4), Rule(516).
Out(v2, v0, v4) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v4), Rule(0).
invent_1(v1, v4) :- In(v0, v1, v2, v3), Lt(v3, v4), Lt(v5, v4), Rule(500).
Out(v5, v4, v2) :- Out(v0, v1, v2), Out(v3, v2, v4), invent_1(v5, v1), Rule(2).
invent_1(v3, v1) :- invent_1(v0, v1), Out(v0, v2, v1), invent_1(v3, v2), Rule(311).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v1, v0), invent_1(v2, v3), Rule(525).
invent_1(v0, v5) :- Out(v0, v1, v2), Out(v0, v2, v3), Out(v4, v3, v5), Rule(334).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v1, v0), Out(v2, v3, v4), Rule(51).
Out(v3, v4, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(213).
Out(v2, v4, v0) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v4), Rule(65).
Out(v2, v4, v1) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v3, v4), Rule(19).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v3), Rule(256).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v3), Rule(228).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v0, v2), Rule(168).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v0, v1), invent_1(v2, v3), Rule(241).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v1, v4), Rule(235).
invent_1(v3, v1) :- Lt(v0, v1), Out(v2, v0, v1), invent_1(v3, v0), Rule(111).
invent_1(v0, v4) :- Out(v0, v1, v2), Out(v3, v1, v4), invent_1(v0, v5), Rule(435).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v1), Rule(333).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v0, v3), Rule(404).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v4), Rule(397).
Out(v2, v1, v3) :- invent_1(v0, v1), invent_1(v2, v1), invent_1(v2, v3), Rule(451).
Out(v2, v3, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v4), Rule(460).
invent_1(v2, v5) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v5, v1), Rule(84).
invent_1(v0, v4) :- Out(v0, v1, v2), invent_1(v0, v1), Out(v3, v1, v4), Rule(221).
Out(v0, v2, v1) :- Out(v0, v1, v2), invent_1(v3, v1), invent_1(v0, v2), Rule(26).
invent_1(v3, v2) :- invent_1(v0, v1), Out(v0, v1, v2), Out(v3, v4, v1), Rule(222).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v1), Rule(448).
Out(v2, v3, v5) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v5), Rule(651).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v4), Rule(680).
invent_1(v1, v6) :- In(v0, v1, v2, v3), Out(v4, v3, v5), Lt(v5, v6), Rule(258).
Out(v3, v1, v0) :- Lt(v0, v1), invent_1(v2, v1), invent_1(v3, v0), Rule(576).
invent_1(v0, v4) :- Out(v0, v1, v2), Out(v0, v3, v1), Lt(v1, v4), Rule(379).
invent_1(v1, v6) :- In(v0, v1, v2, v3), Lt(v3, v4), Out(v5, v4, v6), Rule(198).
Out(v4, v3, v0) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v5, v0), Rule(515).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v0, v2), Rule(160).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v1), Out(v2, v3, v4), Rule(396).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v5, v0), Rule(336).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(231).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v4), Rule(27).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v0, v3), Out(v2, v1, v4), Rule(95).
Out(v4, v3, v5) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v5, v0), Rule(403).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v4, v2), Rule(644).
invent_1(v2, v3) :- Lt(v0, v1), Out(v2, v1, v0), Lt(v0, v3), Rule(412).
Out(v4, v3, v0) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v3), Rule(77).
invent_1(v0, v3) :- Out(v0, v1, v1), invent_1(v2, v1), invent_1(v2, v3), Rule(245).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v4, v2), Rule(315).
invent_1(v5, v2) :- Out(v0, v1, v2), Out(v3, v4, v1), Out(v5, v6, v4), Rule(276).
Out(v2, v0, v1) :- Lt(v0, v1), Out(v2, v3, v4), invent_1(v2, v0), Rule(199).
Out(v3, v1, v4) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v4), Rule(242).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v1, v2), Rule(477).
Out(v4, v3, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v3), Rule(143).
invent_1(v4, v2) :- Out(v0, v1, v2), Out(v3, v2, v1), invent_1(v4, v1), Rule(682).
invent_1(v0, v3) :- invent_1(v0, v1), Out(v0, v1, v2), Lt(v3, v2), Rule(583).
Out(v0, v3, v4) :- Out(v0, v1, v2), Out(v0, v2, v3), Lt(v3, v4), Rule(110).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v0, v2), invent_1(v3, v2), Rule(361).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v0, v2), Out(v3, v2, v4), Rule(486).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(42).
invent_1(v4, v2) :- Out(v0, v1, v2), invent_1(v0, v3), Out(v4, v3, v1), Rule(533).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v3), Rule(380).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v3), Rule(470).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v1), invent_1(v3, v2), Rule(513).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v3, v1), Out(v4, v3, v0), Rule(349).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v4), Rule(683).
invent_1(v3, v5) :- Out(v0, v1, v2), Out(v3, v1, v4), invent_1(v0, v5), Rule(363).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(589).
Out(v3, v4, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(544).
invent_1(v0, v4) :- invent_1(v0, v1), Out(v0, v1, v2), Out(v3, v4, v2), Rule(384).
invent_1(v2, v3) :- Lt(v0, v1), Out(v2, v0, v1), Lt(v1, v3), Rule(161).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v1, v3), Rule(424).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(259).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v3), Rule(598).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v1, v0), invent_1(v2, v3), Rule(116).
Out(v1, v5, v4) :- In(v0, v1, v2, v3), Lt(v3, v4), Lt(v4, v5), Rule(519).
invent_1(v4, v3) :- Out(v0, v1, v2), Out(v0, v3, v2), invent_1(v4, v1), Rule(308).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v3), Rule(555).
Out(v4, v3, v0) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v0, v2), Rule(425).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v1, v2), Rule(281).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v0, v2), Rule(490).
Out(v2, v1, v4) :- Lt(v0, v1), Out(v2, v0, v0), Out(v3, v1, v4), Rule(141).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v3), Rule(556).
Out(v4, v2, v1) :- Out(v0, v1, v2), invent_1(v3, v1), invent_1(v4, v2), Rule(187).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v2, v1), invent_1(v3, v2), Rule(679).
Out(v0, v2, v1) :- Out(v0, v1, v2), invent_1(v3, v1), invent_1(v0, v4), Rule(342).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v4), Rule(150).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v1), Rule(552).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v4), Rule(61).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v1, v3), Rule(310).
Out(v2, v4, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v4, v3), Rule(453).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v4, v2), Rule(355).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v0), invent_1(v3, v2), Rule(588).
Out(v4, v3, v1) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v0, v3), Rule(437).
invent_1(v3, v1) :- Out(v0, v1, v2), Out(v3, v2, v1), invent_1(v3, v4), Rule(203).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v0), Rule(476).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v3), Rule(75).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v1, v3), Out(v2, v4, v0), Rule(394).
Out(v2, v3, v1) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v3, v4), Rule(313).
Out(v2, v4, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v4), Rule(156).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v1), Out(v4, v5, v3), Rule(252).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v3), Rule(432).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v4), Rule(681).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v5, v1), Rule(167).
invent_1(v2, v3) :- Lt(v0, v1), Out(v2, v1, v0), Lt(v3, v0), Rule(473).
Out(v3, v1, v2) :- Out(v0, v1, v2), invent_1(v0, v2), invent_1(v3, v1), Rule(263).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v0, v2), Out(v3, v2, v0), Rule(66).
Out(v3, v0, v1) :- Lt(v0, v1), invent_1(v2, v0), invent_1(v3, v1), Rule(597).
invent_1(v1, v5) :- In(v0, v1, v2, v3), invent_1(v1, v4), Lt(v4, v5), Rule(13).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v3), Rule(345).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(419).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v0, v2), Rule(568).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v3, v3), Rule(237).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v1, v0), Out(v2, v3, v4), Rule(101).
Out(v2, v1, v0) :- Lt(v0, v1), invent_1(v2, v0), invent_1(v2, v1), Rule(47).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v1, v1), invent_1(v2, v3), Rule(214).
invent_1(v5, v4) :- Out(v0, v1, v2), Out(v3, v4, v2), invent_1(v5, v1), Rule(482).
Out(v2, v4, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v4), Rule(48).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v4), Rule(196).
invent_1(v3, v1) :- Lt(v0, v1), Out(v2, v0, v1), Out(v3, v0, v4), Rule(581).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v3), Rule(578).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v1, v2), invent_1(v3, v2), Rule(641).
invent_1(v5, v2) :- Out(v0, v1, v2), Out(v3, v2, v4), invent_1(v5, v1), Rule(326).
invent_1(v1, v3) :- In(v0, v1, v2, v3), Rule(294).
Out(v4, v0, v3) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v3), Rule(360).
Out(v2, v3, v0) :- Lt(v0, v1), Lt(v1, v0), Out(v2, v1, v3), Rule(491).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v1, v1), invent_1(v3, v0), Rule(113).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v0, v2), invent_1(v3, v2), Rule(29).
invent_1(v3, v4) :- Out(v0, v1, v2), Out(v3, v2, v1), Lt(v2, v4), Rule(158).
Out(v2, v1, v5) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v5), Rule(249).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v0, v1), invent_1(v2, v3), Rule(642).
invent_1(v3, v0) :- Lt(v0, v1), Out(v2, v1, v0), invent_1(v3, v1), Rule(638).
Out(v4, v2, v1) :- Out(v0, v1, v2), invent_1(v3, v2), invent_1(v4, v1), Rule(511).
Out(v4, v1, v5) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v5, v3), Rule(472).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v3, v1), Out(v4, v0, v3), Rule(179).
Out(v4, v3, v0) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v0, v3), Rule(665).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v4, v3), Rule(454).
Out(v4, v1, v2) :- Out(v0, v1, v2), invent_1(v3, v1), invent_1(v4, v2), Rule(273).
invent_1(v2, v0) :- Lt(v0, v1), Lt(v1, v0), Out(v2, v1, v3), Rule(285).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v3, v5), Rule(220).
Out(v3, v0, v4) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v4, v2), Rule(496).
invent_1(v0, v3) :- Out(v0, v1, v2), Out(v0, v3, v1), invent_1(v4, v3), Rule(391).
Out(v2, v3, v0) :- Lt(v0, v1), invent_1(v2, v1), Out(v2, v1, v3), Rule(684).
Out(v3, v1, v4) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v4), Rule(551).
Out(v0, v2, v1) :- Out(v0, v1, v2), invent_1(v0, v1), invent_1(v3, v2), Rule(337).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v5, v3), Rule(39).
invent_1(v3, v0) :- Lt(v0, v1), Out(v2, v1, v0), Out(v3, v4, v1), Rule(14).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v5, v0), Rule(471).
invent_1(v2, v1) :- Lt(v0, v1), invent_1(v2, v0), In(v3, v2, v4, v1), Rule(304).
Out(v3, v1, v2) :- Out(v0, v1, v2), invent_1(v0, v1), invent_1(v3, v2), Rule(567).
invent_1(v3, v4) :- Out(v0, v1, v2), invent_1(v3, v1), Out(v3, v2, v4), Rule(468).
Out(v4, v2, v3) :- Out(v0, v1, v2), Out(v0, v2, v3), invent_1(v4, v1), Rule(506).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(340).
invent_1(v3, v4) :- Out(v0, v1, v2), invent_1(v3, v1), Out(v3, v4, v2), Rule(362).
invent_1(v0, v2) :- invent_1(v0, v1), Out(v0, v1, v2), Out(v3, v4, v2), Rule(136).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v4), Rule(138).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v1), Rule(383).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v3), Rule(118).
Out(v2, v0, v5) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v5), Rule(188).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v1, v0), invent_1(v2, v3), Rule(411).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v1), Rule(279).
invent_1(v3, v2) :- Out(v0, v1, v2), invent_1(v3, v1), invent_1(v3, v4), Rule(524).
Out(v3, v4, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v4), Rule(142).
Out(v4, v3, v1) :- Out(v0, v1, v2), Out(v0, v2, v3), invent_1(v4, v1), Rule(80).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v0, v2), Out(v3, v2, v2), Rule(298).
invent_1(v4, v3) :- Out(v0, v1, v2), invent_1(v0, v3), Out(v4, v1, v3), Rule(8).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v5, v3), Rule(507).
Out(v3, v2, v1) :- Out(v0, v1, v2), invent_1(v3, v4), invent_1(v3, v1), Rule(526).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v3), Rule(133).
Out(v0, v4, v1) :- Out(v0, v1, v2), Out(v3, v2, v4), invent_1(v0, v1), Rule(408).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v0, v1), Out(v3, v4, v1), Rule(176).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v5), Rule(616).
Out(v4, v1, v5) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v5), Rule(564).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v1), Rule(157).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v0, v2), Rule(153).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v1, v0), Out(v3, v4, v0), Rule(438).
invent_1(v3, v2) :- Out(v0, v1, v2), Out(v3, v1, v1), invent_1(v4, v2), Rule(277).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v4, v2), Rule(609).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v3), Rule(309).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v4, v1), Rule(545).
Out(v2, v1, v4) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v4), Rule(606).
invent_1(v2, v0) :- Lt(v0, v1), invent_1(v2, v1), Out(v2, v3, v0), Rule(36).
invent_1(v0, v4) :- Out(v0, v1, v2), invent_1(v0, v2), Out(v3, v2, v4), Rule(306).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v1, v2), invent_1(v3, v2), Rule(540).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v1, v2), invent_1(v3, v2), Rule(68).
Out(v4, v0, v5) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v3, v5), Rule(76).
Out(v0, v4, v3) :- Out(v0, v1, v2), Out(v0, v2, v3), Lt(v3, v4), Rule(405).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(106).
Out(v2, v4, v1) :- Lt(v0, v1), Out(v2, v0, v3), Lt(v4, v3), Rule(548).
Out(v2, v4, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v1, v4), Rule(440).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v4), Rule(278).
invent_1(v2, v1) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v1, v3), Rule(303).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v3), Rule(62).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v4), Rule(181).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v3), Rule(55).
invent_1(v5, v3) :- Out(v0, v1, v2), Out(v0, v3, v4), invent_1(v5, v1), Rule(648).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v3), Rule(215).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v1, v2), Rule(370).
invent_1(v2, v3) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v3, v1), Rule(165).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v0, v2), invent_1(v3, v2), Rule(463).
invent_1(v2, v3) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v1, v3), Rule(15).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v2), Rule(71).
invent_1(v5, v4) :- Out(v0, v1, v2), Out(v0, v3, v4), invent_1(v5, v1), Rule(211).
Out(v0, v2, v1) :- Out(v0, v1, v2), Rule(364).
Out(v0, v1, v4) :- Out(v0, v1, v2), Out(v3, v2, v4), invent_1(v0, v1), Rule(569).
Out(v1, v4, v5) :- In(v0, v1, v2, v3), Lt(v3, v4), Lt(v4, v5), Rule(559).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v3, v0), Rule(32).
invent_1(v3, v2) :- Out(v0, v1, v2), Out(v3, v1, v4), invent_1(v5, v2), Rule(209).
invent_1(v3, v1) :- invent_1(v0, v1), invent_1(v0, v2), Out(v3, v2, v1), Rule(462).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(535).
Out(v3, v0, v4) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(234).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v1), Rule(202).
invent_1(v3, v1) :- Out(v0, v1, v2), invent_1(v3, v2), invent_1(v3, v4), Rule(194).
invent_1(v3, v1) :- invent_1(v0, v1), invent_1(v0, v2), invent_1(v3, v2), Rule(23).
Out(v3, v1, v4) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v4, v2), Rule(400).
invent_1(v2, v5) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v5, v1), Rule(107).
Out(v2, v3, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v0), Rule(229).
Out(v2, v0, v3) :- Lt(v0, v1), invent_1(v2, v1), invent_1(v2, v3), Rule(520).
invent_1(v4, v3) :- Out(v0, v1, v2), Out(v0, v3, v1), invent_1(v4, v1), Rule(595).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v2, v0), invent_1(v3, v2), Rule(293).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v3), Rule(382).
Out(v2, v3, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(654).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v0, v0), invent_1(v2, v3), Rule(658).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v0, v2), Out(v3, v1, v2), Rule(25).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v3), Rule(457).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(414).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v1, v2), Rule(443).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v1), Rule(426).
Out(v4, v0, v3) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v3, v0), Rule(378).
invent_1(v0, v2) :- Out(v0, v1, v2), Rule(70).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v0), Rule(537).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v1, v3), Out(v2, v0, v4), Rule(422).
Out(v2, v4, v0) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v1, v4), Rule(430).
invent_1(v3, v0) :- Lt(v0, v1), Out(v2, v0, v1), invent_1(v3, v1), Rule(580).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v1, v3), Rule(238).
Out(v2, v3, v0) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v3), Rule(182).
invent_1(v1, v4) :- In(v0, v1, v2, v3), Lt(v3, v4), Lt(v4, v5), Rule(299).
Out(v2, v0, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v1), Rule(557).
invent_1(v3, v4) :- Out(v0, v1, v2), Out(v3, v2, v1), Lt(v1, v4), Rule(166).
Out(v2, v0, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v4), Rule(21).
invent_1(v2, v3) :- Lt(v0, v1), invent_1(v2, v1), Out(v2, v0, v3), Rule(145).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v0, v2), invent_1(v3, v2), Rule(655).
Out(v2, v3, v1) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v3, v0), Rule(687).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v0, v2), Rule(307).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v1), invent_1(v3, v2), Rule(441).
invent_1(v3, v2) :- invent_1(v0, v1), Out(v0, v2, v1), invent_1(v3, v1), Rule(388).
Out(v2, v5, v3) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v5), Rule(493).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v1), Rule(206).
Out(v2, v3, v0) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v2, v0), Rule(7).
invent_1(v4, v3) :- Out(v0, v1, v2), invent_1(v0, v3), invent_1(v4, v1), Rule(343).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v2, v1, v4), Rule(659).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v1), Rule(79).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v1, v2), Rule(421).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v2, v1), invent_1(v3, v2), Rule(186).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v1), Rule(377).
invent_1(v5, v2) :- Out(v0, v1, v2), Out(v3, v4, v1), Out(v5, v2, v4), Rule(162).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v0, v2), invent_1(v3, v2), Rule(88).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v0, v3), Out(v2, v4, v1), Rule(635).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v5, v3), Rule(344).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v5), Rule(291).
Out(v2, v4, v0) :- Lt(v0, v1), Out(v2, v3, v4), invent_1(v2, v0), Rule(549).
invent_1(v4, v3) :- Out(v0, v1, v2), invent_1(v0, v3), invent_1(v4, v2), Rule(547).
invent_1(v3, v5) :- Out(v0, v1, v2), Out(v3, v4, v1), Out(v3, v2, v5), Rule(22).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v1), Out(v4, v3, v0), Rule(9).
Out(v3, v2, v1) :- Out(v0, v1, v2), invent_1(v0, v2), invent_1(v3, v1), Rule(30).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v4, v1), Rule(645).
Out(v3, v4, v1) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v4), Rule(393).
invent_1(v0, v4) :- Out(v0, v1, v2), Out(v3, v2, v4), invent_1(v0, v5), Rule(487).
invent_1(v4, v2) :- Out(v0, v1, v1), Out(v0, v2, v3), invent_1(v4, v1), Rule(16).
invent_1(v0, v4) :- Out(v0, v1, v2), invent_1(v0, v1), Out(v3, v4, v1), Rule(57).
Out(v4, v0, v3) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v3, v0), Rule(45).
Out(v2, v1, v4) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v4, v3), Rule(375).
invent_1(v2, v3) :- Lt(v0, v1), Out(v2, v0, v1), Lt(v3, v1), Rule(170).
invent_1(v3, v1) :- Lt(v0, v1), Out(v2, v1, v0), invent_1(v3, v0), Rule(632).
Out(v3, v4, v2) :- Out(v0, v1, v2), invent_1(v3, v1), invent_1(v3, v4), Rule(28).
invent_1(v4, v1) :- Out(v0, v1, v2), invent_1(v0, v3), invent_1(v4, v3), Rule(204).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v0, v3), Rule(570).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v3), Rule(154).
Out(v2, v0, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v1), Rule(100).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v0, v0), invent_1(v2, v3), Rule(72).
invent_1(v0, v3) :- Out(v0, v1, v2), Out(v0, v3, v1), Lt(v4, v3), Rule(83).
invent_1(v2, v3) :- Lt(v0, v1), Out(v2, v1, v0), Lt(v1, v3), Rule(123).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v0), Rule(612).
Out(v2, v1, v0) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v1), Rule(90).
invent_1(v4, v3) :- Out(v0, v1, v2), Out(v0, v2, v3), Out(v4, v1, v5), Rule(601).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v0, v2), Out(v3, v2, v0), Rule(49).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(132).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v3), Rule(542).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v0), Rule(415).
invent_1(v4, v3) :- Out(v0, v1, v2), invent_1(v0, v3), Out(v4, v3, v1), Rule(573).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v5, v3), Rule(102).
invent_1(v4, v3) :- Out(v0, v1, v2), Out(v0, v2, v3), Out(v4, v5, v1), Rule(661).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v2), Rule(686).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(86).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v3), Rule(446).
invent_1(v1, v4) :- In(v0, v1, v2, v3), invent_1(v1, v3), Lt(v3, v4), Rule(534).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v1), Out(v4, v0, v3), Rule(667).
invent_1(v2, v0) :- Lt(v0, v1), Lt(v1, v0), Out(v2, v3, v1), Rule(226).
invent_1(v3, v2) :- Out(v0, v1, v2), invent_1(v3, v1), Out(v3, v4, v2), Rule(174).
invent_1(v4, v3) :- Out(v0, v1, v2), Out(v0, v2, v3), invent_1(v4, v2), Rule(656).
invent_1(v5, v4) :- Out(v0, v1, v2), Out(v3, v1, v4), invent_1(v5, v2), Rule(286).
invent_1(v2, v4) :- Out(v0, v1, v1), Out(v2, v1, v3), invent_1(v0, v4), Rule(335).
Out(v3, v1, v4) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(657).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v1), Rule(368).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v1), Rule(449).
Out(v2, v0, v1) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(316).
Out(v2, v0, v1) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v0), Rule(434).
Out(v0, v4, v2) :- Out(v0, v1, v2), invent_1(v0, v1), Out(v3, v2, v4), Rule(346).
Out(v3, v0, v4) :- Lt(v0, v1), Lt(v0, v2), Out(v3, v2, v4), Rule(78).
Out(v4, v3, v0) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v0), Rule(359).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v5, v1), Rule(528).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v4, v2), Rule(678).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v3, v0), Rule(44).
invent_1(v3, v1) :- Lt(v0, v1), Out(v2, v1, v0), Out(v3, v0, v4), Rule(618).
invent_1(v4, v3) :- Out(v0, v1, v1), Out(v0, v2, v3), invent_1(v4, v1), Rule(444).
Out(v2, v0, v4) :- Lt(v0, v1), Out(v2, v0, v1), Out(v3, v1, v4), Rule(254).
Out(v2, v1, v0) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v0), Rule(6).
Out(v0, v1, v3) :- Out(v0, v1, v2), invent_1(v0, v2), Lt(v1, v3), Rule(192).
Out(v2, v0, v1) :- Lt(v0, v1), invent_1(v2, v0), invent_1(v2, v1), Rule(416).
invent_1(v0, v3) :- invent_1(v0, v1), Out(v0, v2, v1), Lt(v2, v3), Rule(501).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v5), Rule(302).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v1, v3), Out(v2, v0, v4), Rule(629).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v4, v2), Rule(60).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(536).
invent_1(v1, v5) :- In(v0, v1, v2, v3), Lt(v3, v4), Out(v1, v4, v5), Rule(431).
Out(v2, v1, v4) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v4), Rule(275).
invent_1(v3, v2) :- Out(v0, v1, v2), Out(v3, v4, v1), invent_1(v5, v2), Rule(669).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v0, v2), Out(v3, v4, v2), Rule(193).
invent_1(v3, v4) :- Out(v0, v1, v2), Out(v3, v1, v2), invent_1(v0, v4), Rule(283).
Out(v4, v3, v1) :- Out(v0, v1, v2), invent_1(v0, v3), invent_1(v4, v1), Rule(626).
Out(v4, v1, v3) :- Out(v0, v1, v2), Out(v0, v2, v3), invent_1(v4, v1), Rule(287).
Out(v4, v5, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v5, v3), Rule(301).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v3), Rule(216).
invent_1(v5, v4) :- Out(v0, v1, v2), Out(v3, v2, v4), invent_1(v5, v1), Rule(619).
invent_1(v3, v4) :- Out(v0, v1, v2), Out(v3, v1, v1), invent_1(v0, v4), Rule(562).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v4), Rule(475).
Out(v4, v3, v2) :- Out(v0, v1, v2), Out(v0, v2, v3), invent_1(v4, v1), Rule(262).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v2), Rule(137).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v3), Rule(289).
Out(v2, v0, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v1), Rule(327).
Out(v3, v0, v4) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(674).
Out(v2, v3, v1) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v1, v3), Rule(399).
Out(v0, v2, v3) :- Out(v0, v1, v2), invent_1(v0, v1), Lt(v2, v3), Rule(271).
invent_1(v0, v2) :- invent_1(v0, v1), Out(v0, v1, v2), Out(v3, v2, v4), Rule(151).
Out(v4, v3, v2) :- Out(v0, v1, v2), invent_1(v0, v3), invent_1(v4, v1), Rule(185).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v2, v1), invent_1(v3, v2), Rule(197).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v1), Rule(531).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v4), Rule(374).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v0, v1), invent_1(v2, v3), Rule(596).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(59).
Out(v0, v2, v4) :- Out(v0, v1, v2), invent_1(v0, v1), Out(v3, v2, v4), Rule(173).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v3), Rule(497).
Out(v3, v0, v1) :- Lt(v0, v1), invent_1(v2, v1), invent_1(v3, v0), Rule(330).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v2, v0), invent_1(v3, v2), Rule(366).
Out(v4, v5, v3) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v5, v0), Rule(611).
Out(v2, v1, v4) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v3, v4), Rule(177).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v3), Rule(122).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v0, v2), invent_1(v3, v2), Rule(64).
invent_1(v3, v1) :- invent_1(v0, v1), invent_1(v0, v2), Out(v3, v1, v2), Rule(135).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v1), Rule(253).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v4), Rule(250).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v3), Rule(191).
Out(v2, v0, v4) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v4), Rule(266).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v1, v2), invent_1(v3, v2), Rule(351).
invent_1(v2, v0) :- Lt(v0, v1), Lt(v1, v0), invent_1(v2, v1), Rule(625).
invent_1(v0, v2) :- Out(v0, v1, v2), invent_1(v3, v2), invent_1(v0, v4), Rule(523).
Out(v2, v4, v3) :- Lt(v0, v1), Out(v2, v0, v3), Out(v2, v1, v4), Rule(322).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v0, v1), invent_1(v2, v3), Rule(114).
invent_1(v3, v1) :- Lt(v0, v1), Out(v2, v0, v1), Out(v3, v4, v0), Rule(639).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v1), Rule(130).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v2), Rule(485).
invent_1(v3, v0) :- Lt(v0, v1), Out(v2, v1, v0), Out(v3, v1, v4), Rule(574).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v0, v2), invent_1(v3, v2), Rule(418).
invent_1(v0, v3) :- Out(v0, v1, v2), Out(v0, v2, v3), Lt(v4, v3), Rule(495).
Out(v2, v0, v1) :- Lt(v0, v1), Out(v2, v1, v0), invent_1(v2, v3), Rule(219).
invent_1(v0, v5) :- Out(v0, v1, v2), invent_1(v0, v3), Out(v4, v3, v5), Rule(269).
Out(v2, v0, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v4), Rule(442).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(685).
Out(v1, v5, v3) :- In(v0, v1, v2, v3), Lt(v3, v4), Lt(v4, v5), Rule(499).
Out(v2, v1, v3) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v0, v3), Rule(461).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v0, v3), Rule(623).
invent_1(v0, v5) :- Out(v0, v1, v1), Out(v2, v1, v3), Out(v4, v3, v5), Rule(447).
invent_1(v2, v3) :- Lt(v0, v1), Out(v2, v0, v1), Lt(v3, v0), Rule(321).
Out(v5, v2, v4) :- Out(v0, v1, v2), Out(v3, v2, v4), invent_1(v5, v1), Rule(395).
invent_1(v2, v3) :- Lt(v0, v1), Out(v2, v1, v0), Lt(v3, v1), Rule(292).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v1), Rule(272).
invent_1(v3, v5) :- Out(v0, v1, v2), Out(v3, v2, v1), Out(v4, v2, v5), Rule(624).
invent_1(v3, v4) :- Out(v0, v1, v2), Out(v3, v2, v1), invent_1(v0, v4), Rule(652).
invent_1(v4, v3) :- Out(v0, v1, v2), Out(v0, v1, v3), invent_1(v4, v2), Rule(389).
Out(v2, v0, v3) :- Lt(v0, v1), invent_1(v2, v1), Out(v2, v1, v3), Rule(455).
Out(v2, v0, v3) :- Lt(v0, v1), invent_1(v2, v0), invent_1(v2, v3), Rule(24).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v1), Rule(582).
Out(v4, v5, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v5), Rule(295).
Out(v2, v5, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v5), Rule(50).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v1), Rule(81).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v0, v3), Rule(183).
Out(v2, v4, v1) :- Lt(v0, v1), Out(v2, v0, v0), Out(v3, v1, v4), Rule(260).
Out(v1, v3, v5) :- In(v0, v1, v2, v3), Lt(v3, v4), Lt(v4, v5), Rule(376).
invent_1(v0, v3) :- Out(v0, v1, v2), Out(v0, v2, v3), Lt(v3, v4), Rule(139).
Out(v2, v1, v0) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v4), Rule(550).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v0, v0), Out(v3, v4, v1), Rule(600).
invent_1(v3, v1) :- Lt(v0, v1), Out(v2, v1, v0), Out(v3, v4, v0), Rule(175).
Out(v2, v0, v1) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v2, v0), Rule(662).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v1, v4), Rule(43).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v2), Rule(144).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v1, v2), Rule(149).
Out(v0, v3, v2) :- Out(v0, v1, v2), invent_1(v0, v1), Lt(v3, v2), Rule(239).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v0), Rule(673).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v0, v1), Out(v3, v0, v4), Rule(628).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v3), Rule(599).
Out(v3, v4, v0) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v4), Rule(324).
Out(v2, v4, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v2, v1, v4), Rule(117).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v2, v4), Rule(452).
invent_1(v3, v1) :- invent_1(v0, v1), Out(v0, v2, v1), Out(v3, v2, v4), Rule(108).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v0), Rule(631).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v4), Rule(46).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(41).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v1), Rule(675).
invent_1(v0, v2) :- invent_1(v0, v1), Out(v0, v1, v2), Lt(v3, v2), Rule(89).
Out(v4, v0, v3) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(1).
invent_1(v3, v2) :- Out(v0, v1, v1), invent_1(v0, v2), invent_1(v3, v1), Rule(387).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v1, v0), invent_1(v2, v3), Rule(318).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v1), Rule(40).
Out(v4, v2, v1) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v0, v2), Rule(290).
Out(v2, v1, v3) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v3, v0), Rule(178).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v2, v0), invent_1(v3, v2), Rule(390).
Out(v3, v4, v1) :- Out(v0, v1, v2), invent_1(v3, v4), invent_1(v3, v1), Rule(512).
invent_1(v0, v3) :- Out(v0, v1, v2), Out(v0, v2, v3), invent_1(v4, v3), Rule(429).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v1), Rule(666).
Out(v3, v2, v1) :- invent_1(v0, v1), invent_1(v0, v2), invent_1(v3, v2), Rule(332).
invent_1(v0, v4) :- invent_1(v0, v1), Out(v0, v1, v2), Out(v3, v2, v4), Rule(592).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(604).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v0), Rule(409).
Out(v2, v1, v0) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v4), Rule(5).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v1, v0), invent_1(v2, v3), Rule(300).
invent_1(v5, v4) :- Out(v0, v1, v2), Out(v3, v2, v4), Out(v5, v1, v4), Rule(246).
Out(v4, v1, v3) :- Out(v0, v1, v2), invent_1(v0, v3), invent_1(v4, v1), Rule(53).
invent_1(v0, v2) :- invent_1(v0, v1), Out(v0, v2, v1), invent_1(v3, v2), Rule(590).
Out(v2, v3, v0) :- Lt(v0, v1), Lt(v1, v0), Out(v2, v3, v1), Rule(35).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v4, v2), Rule(577).
invent_1(v0, v3) :- Out(v0, v1, v2), invent_1(v0, v1), Lt(v3, v1), Rule(134).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v2, v0), Rule(584).
Out(v2, v1, v4) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v3, v4), Rule(621).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v1, v0), Out(v3, v0, v4), Rule(17).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v0), invent_1(v3, v1), Rule(205).
invent_1(v3, v1) :- invent_1(v0, v1), Out(v0, v2, v1), Out(v3, v4, v2), Rule(608).
Out(v4, v0, v3) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v0, v2), Rule(284).
invent_1(v2, v1) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v3, v4), Rule(282).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v1, v2), Rule(11).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v0), Rule(341).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v2), Rule(248).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v1), Rule(189).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v5, v3), Rule(488).
Out(v2, v3, v0) :- Lt(v0, v1), invent_1(v2, v0), invent_1(v2, v3), Rule(323).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v4), Rule(172).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v0, v2), invent_1(v3, v2), Rule(155).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v4, v2), Rule(314).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v2), Rule(436).
Out(v2, v4, v3) :- Lt(v0, v1), Out(v2, v1, v3), Out(v2, v4, v0), Rule(649).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(633).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v2, v0), invent_1(v3, v2), Rule(121).
Out(v4, v2, v0) :- Lt(v0, v1), Lt(v2, v3), Out(v4, v3, v0), Rule(413).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v1, v2), invent_1(v3, v2), Rule(352).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v3), Rule(338).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v3), Rule(120).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v3, v1), Rule(522).
Out(v2, v3, v0) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v3), Rule(427).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v1), Rule(539).
Out(v2, v1, v3) :- Lt(v0, v1), invent_1(v2, v1), invent_1(v2, v3), Rule(159).
Out(v2, v0, v4) :- Lt(v0, v1), Out(v2, v3, v4), invent_1(v2, v0), Rule(647).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v0), invent_1(v3, v2), Rule(538).
invent_1(v1, v4) :- In(v0, v1, v2, v3), Lt(v3, v4), invent_1(v5, v4), Rule(481).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v2), Rule(660).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v0), Rule(152).
invent_1(v0, v1) :- Out(v0, v1, v2), Rule(610).
invent_1(v0, v3) :- Out(v0, v1, v2), Out(v0, v1, v3), Lt(v4, v3), Rule(358).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v2, v4), Rule(465).
Out(v2, v0, v4) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v1, v4), Rule(518).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v4, v2), Rule(112).
Out(v3, v4, v1) :- Out(v0, v1, v2), Out(v3, v2, v4), invent_1(v3, v1), Rule(105).
Out(v2, v0, v4) :- Lt(v0, v1), Out(v2, v0, v3), Out(v2, v1, v4), Rule(223).
invent_1(v2, v4) :- Out(v0, v1, v1), Out(v2, v3, v1), invent_1(v0, v4), Rule(571).
Out(v2, v1, v0) :- Lt(v0, v1), Out(v2, v3, v4), invent_1(v2, v0), Rule(270).
Out(v3, v0, v2) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v4), Rule(420).
Out(v2, v3, v4) :- Lt(v0, v1), Out(v2, v1, v3), Out(v2, v4, v0), Rule(317).
invent_1(v1, v5) :- In(v0, v1, v2, v3), Lt(v3, v4), Lt(v4, v5), Rule(483).
Out(v2, v1, v3) :- Lt(v0, v1), invent_1(v2, v0), invent_1(v2, v3), Rule(593).
invent_1(v0, v3) :- Out(v0, v1, v2), invent_1(v0, v2), Lt(v2, v3), Rule(94).
invent_1(v5, v4) :- In(v0, v1, v2, v3), invent_1(v1, v4), invent_1(v5, v3), Rule(386).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v1), Rule(585).
invent_1(v0, v3) :- Out(v0, v1, v2), Out(v0, v1, v3), Lt(v3, v4), Rule(646).
Out(v3, v4, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(255).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v4), Rule(4).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v5, v3), Rule(69).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v3, v0), Rule(653).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v4, v2), Rule(494).
invent_1(v2, v0) :- Lt(v0, v1), Out(v2, v1, v1), invent_1(v2, v3), Rule(672).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v2, v0), invent_1(v3, v2), Rule(381).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v2, v4, v3), Rule(97).
Out(v2, v0, v3) :- Lt(v0, v1), Lt(v1, v0), Out(v2, v1, v3), Rule(423).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v1, v0), Out(v3, v4, v1), Rule(530).
Out(v2, v0, v4) :- Lt(v0, v1), Out(v2, v1, v0), Out(v3, v1, v4), Rule(561).
Out(v4, v1, v2) :- Out(v0, v1, v2), invent_1(v3, v2), invent_1(v4, v1), Rule(140).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v1, v3), Rule(505).
Out(v2, v4, v1) :- Lt(v0, v1), Out(v2, v3, v0), Lt(v4, v3), Rule(664).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v4), Rule(350).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v1, v3), Out(v4, v5, v0), Rule(91).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v3, v0), invent_1(v4, v1), Rule(458).
invent_1(v3, v1) :- Lt(v0, v1), invent_1(v2, v1), invent_1(v3, v0), Rule(93).
Out(v2, v5, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v5, v3), Rule(127).
invent_1(v0, v2) :- invent_1(v0, v1), Out(v0, v1, v2), Lt(v2, v3), Rule(171).
invent_1(v4, v2) :- Out(v0, v1, v2), invent_1(v0, v3), invent_1(v4, v3), Rule(354).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v1, v2), Rule(63).
Out(v2, v3, v1) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v2, v3), Rule(312).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v2, v4), Rule(677).
Out(v2, v0, v3) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v0), Rule(218).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(148).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v1), Out(v4, v3, v3), Rule(504).
Out(v3, v1, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v2), Rule(456).
invent_1(v3, v1) :- Lt(v0, v1), Lt(v2, v1), Out(v3, v2, v2), Rule(521).
Out(v4, v1, v0) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v3), Rule(34).
invent_1(v4, v1) :- Out(v0, v1, v2), Out(v0, v3, v1), invent_1(v4, v3), Rule(640).
Out(v2, v3, v0) :- Lt(v0, v1), Out(v2, v0, v1), invent_1(v2, v3), Rule(613).
invent_1(v2, v3) :- Lt(v0, v1), Out(v2, v0, v1), Lt(v0, v3), Rule(357).
Out(v3, v2, v1) :- Lt(v0, v1), Lt(v2, v1), invent_1(v3, v2), Rule(184).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v5), Rule(650).
invent_1(v4, v0) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v3), Rule(503).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v3, v1), Out(v4, v3, v5), Rule(615).
Out(v2, v1, v3) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v3, v1), Rule(510).
Out(v3, v2, v0) :- Lt(v0, v1), Lt(v1, v2), invent_1(v3, v2), Rule(128).
invent_1(v0, v3) :- invent_1(v0, v1), Out(v0, v2, v1), Lt(v3, v2), Rule(630).
Out(v2, v5, v0) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v5), Rule(3).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v1, v2), Rule(579).
Out(v4, v3, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v3, v5), Rule(459).
Out(v2, v1, v3) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v3), Rule(353).
invent_1(v3, v2) :- invent_1(v0, v1), Out(v0, v1, v2), invent_1(v3, v1), Rule(554).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v4), Rule(207).
invent_1(v3, v4) :- Out(v0, v1, v2), invent_1(v3, v2), Out(v3, v1, v4), Rule(517).
invent_1(v0, v3) :- Out(v0, v1, v2), Out(v0, v1, v3), invent_1(v4, v3), Rule(478).
Out(v3, v1, v2) :- Out(v0, v1, v2), invent_1(v3, v4), invent_1(v3, v1), Rule(129).
invent_1(v0, v3) :- invent_1(v0, v1), Out(v0, v1, v2), Lt(v2, v3), Rule(98).
Out(v2, v1, v0) :- Lt(v0, v1), Out(v2, v0, v1), invent_1(v2, v3), Rule(563).
Out(v3, v1, v4) :- Lt(v0, v1), Lt(v2, v0), Out(v3, v2, v4), Rule(594).
Out(v2, v4, v0) :- Lt(v0, v1), Out(v2, v0, v1), Out(v3, v1, v4), Rule(87).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v1, v0), Out(v3, v1, v4), Rule(670).
Out(v5, v4, v1) :- Out(v0, v1, v2), Out(v3, v2, v4), invent_1(v5, v1), Rule(96).
Out(v3, v0, v1) :- Lt(v0, v1), Lt(v0, v2), Out(v3, v2, v4), Rule(325).
Out(v2, v0, v4) :- Lt(v0, v1), Out(v2, v1, v3), Out(v2, v3, v4), Rule(210).
Out(v3, v1, v2) :- Lt(v0, v1), Lt(v2, v1), invent_1(v3, v2), Rule(103).
invent_1(v1, v5) :- In(v0, v1, v2, v3), Out(v1, v3, v4), Lt(v4, v5), Rule(109).
invent_1(v4, v1) :- Lt(v0, v1), Out(v2, v1, v3), invent_1(v4, v3), Rule(124).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v0, v1), Out(v3, v1, v4), Rule(230).
Out(v3, v2, v1) :- Out(v0, v1, v2), invent_1(v0, v1), invent_1(v3, v2), Rule(428).
invent_1(v3, v1) :- invent_1(v0, v1), Out(v0, v1, v2), invent_1(v3, v2), Rule(224).
Out(v5, v1, v4) :- Out(v0, v1, v2), Out(v3, v2, v4), invent_1(v5, v1), Rule(565).
Out(v4, v2, v3) :- Out(v0, v1, v2), invent_1(v0, v3), invent_1(v4, v1), Rule(265).
Out(v2, v3, v0) :- Lt(v0, v1), Out(v2, v3, v4), invent_1(v2, v0), Rule(10).
invent_1(v3, v0) :- Lt(v0, v1), Lt(v1, v2), Out(v3, v2, v0), Rule(212).
invent_1(v0, v4) :- Out(v0, v1, v2), invent_1(v3, v2), invent_1(v3, v4), Rule(280).
invent_1(v1, v4) :- In(v0, v1, v2, v3), Lt(v3, v4), invent_1(v1, v5), Rule(514).
Out(v3, v1, v4) :- Out(v0, v1, v2), Out(v3, v2, v4), invent_1(v3, v1), Rule(131).
Out(v2, v3, v0) :- Lt(v0, v1), invent_1(v2, v1), invent_1(v2, v3), Rule(558).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v0, v3), Out(v4, v1, v3), Rule(410).
invent_1(v3, v2) :- invent_1(v0, v1), Out(v0, v1, v2), Out(v3, v1, v4), Rule(392).
invent_1(v4, v1) :- Out(v0, v1, v2), invent_1(v3, v1), invent_1(v4, v2), Rule(331).
invent_1(v2, v4) :- Lt(v0, v1), Out(v2, v0, v0), Out(v3, v1, v4), Rule(348).
invent_1(v2, v1) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v3, v1), Rule(450).
invent_1(v3, v2) :- Out(v0, v1, v2), Out(v3, v1, v2), invent_1(v3, v4), Rule(620).
invent_1(v2, v1) :- Lt(v0, v1), Out(v2, v0, v0), Out(v3, v1, v4), Rule(33).
invent_1(v4, v3) :- Lt(v0, v1), Out(v2, v0, v3), invent_1(v4, v1), Rule(602).
Out(v4, v1, v3) :- Lt(v0, v1), Out(v2, v3, v1), invent_1(v4, v0), Rule(67).
Out(v2, v3, v1) :- Lt(v0, v1), invent_1(v2, v0), Out(v2, v0, v3), Rule(474).
Out(v2, v4, v0) :- Lt(v0, v1), Out(v2, v1, v0), Out(v3, v1, v4), Rule(529).
invent_1(v0, v6) :- Out(v0, v1, v2), Out(v3, v1, v4), Out(v5, v4, v6), Rule(73).
Out(v0, v3, v1) :- Out(v0, v1, v2), invent_1(v0, v2), Lt(v1, v3), Rule(417).
Out(v4, v0, v1) :- Lt(v0, v1), Out(v2, v3, v0), Out(v4, v1, v3), Rule(385).
Out(v0, v2, v3) :- Out(v0, v1, v2), invent_1(v0, v1), Lt(v3, v2), Rule(227).
