// Souffle - A Datalog Compiler
// Copyright (c) 2018, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test  multiple input directives
.decl A(x:number, y:number)
.input A
.input A(IO="file",filename="AA.facts")

.decl B(x:number, y:number)
.output B

B(x, y) :- A(x, y).
