#!/usr/bin/env python3

import os
import sys
import subprocess

scriptPath = sys.argv[0]
benchmarks = ["1-call-site", "1-object", "1-object-1-type", "1-type", "2-call-site", "abduce", "andersen", "animals", "buildwall", "clique", "cliquer", "downcast", "escape", "inflamation", "modref", "nearlyscc", "path", "polysite", "rsg", "rvcheck", "scc", "sgen", "ship", "small", "sql-01", "sql-02", "sql-03", "sql-04", "sql-05", "sql-06", "sql-07", "sql-08", "sql-09", "sql-10", "sql-11", "sql-12", "sql-13", "sql-14", "sql-15", "traffic", "union-find"]
scale_benchmarks = ["1-object-1-type_100","1-object-1-type_200","1-object-1-type_300","1-object-1-type_400","1-object-1-type_500","1-object-1-type_600","1-object-1-type_700","1-object-1-type_800","1-object-1-type_900","1-object-1-type_1000","scc_100","scc_200","scc_300","scc_400","scc_500","scc_600","scc_700","scc_800","scc_900","scc_1000"]

f = open("data.log", "w")
f.close()

for benchmark in scale_benchmarks:
	print("Generating souffle executable for [" + benchmark + "]")
	myproc = subprocess.Popen([ './prepare', './scale_benchmarks/' + benchmark ], \
          stdin=subprocess.PIPE, \
          stdout=subprocess.PIPE, \
          universal_newlines=True)
	myproc.communicate()
	print("Generated souffle executable for [" + benchmark + "]!")


for i in range(1, 9):
	for benchmark in scale_benchmarks:
		print("Running ProSynth (delta) for [" + benchmark + "]")
		myproc = subprocess.Popen([ './prosynth', './scale_benchmarks/' + benchmark, "0", "1", str(i) ], \
	          stdin=subprocess.PIPE, \
	          stdout=subprocess.PIPE, \
	          universal_newlines=True)
		myproc.communicate()

for benchmark in benchmarks:
	print("Generating souffle executable for [" + benchmark + "]")
	myproc = subprocess.Popen([ './prepare', './benchmarks/' + benchmark ], \
          stdin=subprocess.PIPE, \
          stdout=subprocess.PIPE, \
          universal_newlines=True)
	myproc.communicate()
	print("Generated souffle executable for [" + benchmark + "]!")

for i in range(1, 33):
	for benchmark in benchmarks:
		print("Running ProSynth (no delta) for [" + benchmark + "]")
		myproc = subprocess.Popen([ './prosynth', './benchmarks/' + benchmark, "0", "0", str(i) ], \
	          stdin=subprocess.PIPE, \
	          stdout=subprocess.PIPE, \
	          universal_newlines=True)
		myproc.communicate()
		print("Running ProSynth (delta) for [" + benchmark + "]")
		myproc = subprocess.Popen([ './prosynth', './benchmarks/' + benchmark, "0", "1", str(i) ], \
	          stdin=subprocess.PIPE, \
	          stdout=subprocess.PIPE, \
	          universal_newlines=True)
		myproc.communicate()


