.type date
.type yrq

.decl Rule(n: number)
.input Rule

.decl LE20130201(v0: date)
.input LE20130201
.decl GE20130215(v0: date)
.input GE20130215
.decl input1(v0: yrq, v1: date, v2: date)
.input input1

.decl output(v0: yrq)
.output output

output(v3) :- GE20130215(v0), input1(v1, v0, v2), input1(v3, v2, v4), Rule(1).
output(v3) :- output(v0), input1(v0, v1, v2), input1(v3, v4, v1), Rule(4).
output(v3) :- GE20130215(v0), input1(v1, v2, v0), input1(v3, v4, v2), Rule(19).
output(v1) :- GE20130215(v0), input1(v1, v0, v2), input1(v3, v2, v4), Rule(20).
output(v1) :- LE20130201(v0), input1(v1, v2, v0), input1(v1, v3, v4), Rule(5).
output(v2) :- GE20130215(v0), LE20130201(v1), input1(v2, v1, v0), Rule(18).
output(v3) :- output(v0), input1(v0, v1, v2), input1(v3, v2, v4), Rule(9).
output(v3) :- GE20130215(v0), input1(v1, v2, v0), input1(v3, v2, v4), Rule(23).
output(v2) :- GE20130215(v0), LE20130201(v1), input1(v2, v0, v1), Rule(13).
output(v5) :- input1(v0, v1, v2), input1(v3, v4, v1), input1(v5, v6, v4), Rule(3).
output(v3) :- GE20130215(v0), input1(v1, v0, v2), input1(v3, v4, v2), Rule(14).
output(v1) :- LE20130201(v0), input1(v1, v0, v2), input1(v3, v2, v4), Rule(11).
output(v1) :- LE20130201(v0), input1(v1, v2, v0), input1(v3, v4, v2), Rule(15).
output(v3) :- LE20130201(v0), input1(v1, v2, v0), input1(v3, v2, v4), Rule(25).
output(v3) :- LE20130201(v0), input1(v1, v0, v2), input1(v3, v4, v2), Rule(22).
output(v3) :- LE20130201(v0), input1(v1, v2, v0), input1(v3, v4, v2), Rule(21).
output(v3) :- output(v0), input1(v0, v1, v2), input1(v3, v4, v2), Rule(17).
output(v2) :- GE20130215(v0), GE20130215(v1), input1(v2, v0, v1), Rule(24).
output(v3) :- output(v0), input1(v0, v1, v2), input1(v3, v1, v4), Rule(12).
output(v2) :- LE20130201(v0), LE20130201(v1), input1(v2, v0, v1), Rule(16).
output(v3) :- LE20130201(v0), input1(v1, v0, v2), input1(v3, v2, v4), Rule(2).
output(v1) :- LE20130201(v0), input1(v1, v0, v2), input1(v1, v3, v4), Rule(6).
output(v1) :- GE20130215(v0), input1(v1, v2, v0), input1(v1, v3, v4), Rule(7).
output(v5) :- input1(v0, v1, v2), input1(v3, v4, v1), input1(v5, v4, v6), Rule(8).
output(v1) :- GE20130215(v0), input1(v1, v2, v0), input1(v3, v4, v2), Rule(10).
output(v1) :- GE20130215(v0), input1(v1, v0, v2), input1(v1, v3, v4), Rule(0).
