#!/usr/bin/env bash

# Clones and builds Souffle and Difflog, and sets up the provenance-aware synthesis system
# Intended to be run from the main directory
# ./scripts/clone

set -e

git clone git://github.com/souffle-lang/souffle.git
pushd souffle
    patch -p1 < ../data/souffle.patch
    ./bootstrap
    ./configure
    make -j 8
popd

git clone git@github.com:difflog-project/qd.git
pushd qd
    git checkout S3
    git pull origin S3
popd
