// Souffle - A Datalog Compiler
// Copyright (c) 2018, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Tests the suppress-warnings pragma option.

.pragma "suppress-warnings" "a,c,k.blah"

// test for regular relations
.decl a(x:number)

.decl b(x:number)

.decl c(x:number)
.output c()

.decl d()

// test on components
.comp A {
    .decl blah(x:number)
    .output blah()
}
.init k = A
.init l = A

