// Souffle - A Datalog Compiler
// Copyright (c) 2017, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

//// Test-case for string matching

.decl inputData(s:symbol)
.input inputData

.decl outputData(s:symbol)
.output outputData

outputData(x) :- inputData(x), !match("a.*", x).
