// Souffle - A Datalog Compiler
// Copyright (c) 2017, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test if sqlite3 IO works

.decl A(x:number)
// Read in from sqlite3 (assumes relative path to test dir is correct
.input A(IO=sqlite,dbname="A.sqlite.input")
// Add a tuple to make sure input and output are different
A(2).
// Write to CSV
.output A(IO=file,filename="AA.csv")
// Write to sqlite3
.output A(IO=sqlite,dbname="BB.sqlite.output")
