// Souffle - A Datalog Compiler
// Copyright (c) 2017, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Check issues with generation of templated eqrel code.
.decl A(a: symbol, b: symbol)
.decl B(h1: symbol, h2: symbol) eqrel

A("a","b").

B(a, b) :-
    A(a, b),
    B(a, _).

B(a, b) :-
    B(a, _),
    A(a, b).

.output B

