// Souffle - A Datalog Compiler
// Copyright (c) 2017, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test csv output with column headers
.decl A(x:number, y:number)
A(1,2).
.output A(IO=file,filename="AA.csv",headers=true)
.output A(IO=file,filename="BB.csv",headers=true,delimiter=BOB)
