#!/usr/bin/env python3

########################################################################################################################
# Log Aggregator

# Invocation: ./log-aggregator logs TRIALS

########################################################################################################################
# 1. Prelude

import json
import logging
import os
import subprocess
import sys
import z3
import time
import copy
import random

currPath = sys.argv[0]
scriptPath = sys.argv[1]
trials = sys.argv[2]

mr = open("runtime.csv", "w")
mz = open("numprograms.csv", "w")

bf = open("benchmarks.txt", "r")
for benchmarkName in bf:
    currRuntimeLine = benchmarkName.strip()
    currProgramsLine = benchmarkName.strip()
    for i in range(int(trials)):
        currBenchName = scriptPath + "/" + benchmarkName.strip() + "-" + str(i+1) + ".log"
        print(currBenchName)

        cf = open(currBenchName, "r")
        myText = cf.read()
        cf.close()

        numProg = myText.count("nextStateMCMC:112") + myText.count("learn:52")
        myText = myText[myText.find("Total time:")+12:]
        myText = myText[:myText.find("s,")]
        totalTime = float(myText)

        currRuntimeLine += "," + str(totalTime)
        currProgramsLine += "," + str(numProg)

        #print("numZ3Calls: " + str(numZ3Calls))
        #print("numSouffleCalls: " + str(numSouffleCalls))
        #print("totalRuntime: " + str(1 + totalRuntime))
        #k = myText.rfind("Total runtime: ")
        
        #m = myText.rfind("Calls to Souffle: ")

        #currRuntime = float(myText[:(k+14)])
        #currRuntime = float(myText[:(k+14)])
    mr.write(currRuntimeLine + "\n")
    mz.write(currProgramsLine + "\n")
bf.close()
mr.close()
mz.close()