.type B
.type D

.decl Rule(n: number)
.input Rule

.decl cont(v0: D)
.input cont
.decl offset(v0: D)
.input offset
.decl fetch(v0: D, v1: B)
.input fetch
.decl putOn(v0: B, v1: D)
.input putOn

.decl invent_2(v0: D, v1: D)
.output invent_2
.decl buildWall(v0: D, v1: D)
.output buildWall

buildWall(v0, v2) :- invent_2(v0, v1), invent_2(v2, v0), Rule(9).
buildWall(v2, v1) :- buildWall(v0, v1), invent_2(v2, v0), offset(v2), Rule(59).
invent_2(v2, v1) :- invent_2(v0, v1), offset(v0), invent_2(v2, v0), Rule(53).
invent_2(v1, v0) :- buildWall(v0, v1), putOn(v2, v0), Rule(107).
invent_2(v0, v1) :- buildWall(v0, v1), invent_2(v2, v1), Rule(159).
invent_2(v2, v0) :- buildWall(v0, v1), offset(v1), buildWall(v2, v0), Rule(154).
buildWall(v0, v2) :- cont(v0), fetch(v0, v1), putOn(v1, v2), Rule(102).
invent_2(v0, v1) :- buildWall(v0, v1), invent_2(v2, v0), Rule(24).
invent_2(v1, v2) :- invent_2(v0, v1), offset(v0), buildWall(v1, v2), Rule(162).
buildWall(v1, v0) :- cont(v0), invent_2(v1, v0), Rule(83).
invent_2(v2, v0) :- buildWall(v0, v1), buildWall(v2, v0), Rule(35).
invent_2(v2, v1) :- buildWall(v0, v1), cont(v0), buildWall(v2, v1), Rule(111).
buildWall(v2, v1) :- invent_2(v0, v1), invent_2(v2, v1), Rule(173).
buildWall(v0, v2) :- buildWall(v0, v1), buildWall(v1, v2), offset(v0), Rule(29).
invent_2(v0, v2) :- buildWall(v0, v1), offset(v1), buildWall(v0, v2), Rule(122).
invent_2(v2, v1) :- buildWall(v0, v1), buildWall(v2, v0), offset(v1), Rule(62).
buildWall(v1, v2) :- buildWall(v0, v1), invent_2(v0, v2), Rule(148).
invent_2(v0, v2) :- invent_2(v0, v1), invent_2(v1, v2), offset(v0), Rule(7).
invent_2(v2, v1) :- buildWall(v0, v1), buildWall(v1, v2), Rule(30).
buildWall(v0, v2) :- fetch(v0, v1), putOn(v1, v2), Rule(70).
invent_2(v0, v2) :- invent_2(v0, v1), invent_2(v2, v0), Rule(36).
buildWall(v2, v1) :- buildWall(v0, v1), offset(v0), invent_2(v2, v0), Rule(89).
invent_2(v0, v2) :- buildWall(v0, v1), invent_2(v1, v2), offset(v0), Rule(124).
invent_2(v0, v1) :- buildWall(v0, v1), cont(v1), Rule(25).
buildWall(v0, v2) :- fetch(v0, v1), invent_2(v2, v0), Rule(135).
invent_2(v0, v2) :- buildWall(v0, v1), cont(v1), invent_2(v1, v2), Rule(84).
buildWall(v2, v1) :- buildWall(v0, v1), buildWall(v2, v0), cont(v1), Rule(19).
invent_2(v2, v1) :- buildWall(v0, v1), offset(v0), buildWall(v2, v1), Rule(163).
invent_2(v0, v2) :- fetch(v0, v1), putOn(v1, v2), offset(v2), Rule(40).
invent_2(v0, v1) :- buildWall(v0, v1), offset(v0), Rule(136).
buildWall(v2, v1) :- buildWall(v0, v1), invent_2(v2, v0), Rule(11).
buildWall(v1, v2) :- buildWall(v0, v1), cont(v0), invent_2(v1, v2), Rule(99).
buildWall(v2, v1) :- buildWall(v0, v1), invent_2(v2, v0), offset(v1), Rule(110).
buildWall(v1, v2) :- buildWall(v0, v1), offset(v0), invent_2(v1, v2), Rule(22).
invent_2(v2, v1) :- invent_2(v0, v1), invent_2(v2, v0), offset(v1), Rule(139).
buildWall(v1, v2) :- buildWall(v0, v1), buildWall(v0, v2), Rule(146).
invent_2(v1, v2) :- buildWall(v0, v1), offset(v0), buildWall(v1, v2), Rule(140).
buildWall(v2, v1) :- buildWall(v0, v1), offset(v0), invent_2(v2, v1), Rule(133).
buildWall(v1, v2) :- invent_2(v0, v1), offset(v0), invent_2(v1, v2), Rule(160).
invent_2(v0, v1) :- buildWall(v0, v1), cont(v0), Rule(129).
invent_2(v0, v1) :- buildWall(v0, v1), fetch(v1, v2), Rule(6).
invent_2(v1, v2) :- buildWall(v0, v1), invent_2(v0, v2), Rule(145).
invent_2(v0, v2) :- invent_2(v0, v1), offset(v1), buildWall(v0, v2), Rule(77).
invent_2(v1, v0) :- buildWall(v0, v1), fetch(v1, v2), Rule(75).
buildWall(v2, v1) :- invent_2(v0, v1), invent_2(v2, v0), Rule(15).
invent_2(v1, v2) :- cont(v0), invent_2(v1, v0), buildWall(v1, v2), Rule(121).
invent_2(v2, v1) :- buildWall(v0, v1), offset(v0), buildWall(v2, v0), Rule(42).
invent_2(v0, v2) :- buildWall(v0, v1), offset(v1), invent_2(v1, v2), Rule(44).
buildWall(v0, v2) :- buildWall(v0, v1), buildWall(v2, v0), Rule(17).
invent_2(v0, v1) :- buildWall(v0, v1), putOn(v2, v0), Rule(137).
buildWall(v0, v2) :- buildWall(v0, v1), invent_2(v1, v2), offset(v2), Rule(119).
buildWall(v0, v2) :- buildWall(v0, v1), offset(v1), invent_2(v0, v2), Rule(39).
buildWall(v0, v2) :- buildWall(v0, v1), invent_2(v1, v2), cont(v2), Rule(134).
buildWall(v2, v0) :- buildWall(v0, v1), invent_2(v2, v0), Rule(172).
invent_2(v0, v2) :- fetch(v0, v1), putOn(v1, v2), Rule(56).
buildWall(v1, v0) :- buildWall(v0, v1), fetch(v1, v2), Rule(46).
buildWall(v1, v2) :- buildWall(v0, v1), invent_2(v1, v2), Rule(45).
buildWall(v2, v0) :- invent_2(v0, v1), offset(v1), invent_2(v2, v0), Rule(142).
invent_2(v0, v2) :- cont(v0), invent_2(v0, v1), invent_2(v1, v2), Rule(118).
buildWall(v2, v1) :- cont(v0), invent_2(v1, v0), invent_2(v2, v1), Rule(117).
invent_2(v0, v2) :- fetch(v0, v1), invent_2(v2, v0), Rule(54).
invent_2(v2, v1) :- invent_2(v0, v1), offset(v0), buildWall(v2, v1), Rule(50).
buildWall(v1, v2) :- buildWall(v0, v1), invent_2(v2, v0), Rule(123).
buildWall(v0, v2) :- cont(v0), invent_2(v0, v1), invent_2(v1, v2), Rule(114).
buildWall(v2, v1) :- buildWall(v0, v1), invent_2(v1, v2), Rule(106).
buildWall(v2, v1) :- buildWall(v0, v1), cont(v0), invent_2(v2, v0), Rule(141).
buildWall(v2, v1) :- invent_2(v0, v1), invent_2(v1, v2), Rule(103).
buildWall(v1, v0) :- invent_2(v0, v1), putOn(v2, v0), Rule(128).
invent_2(v0, v2) :- cont(v0), fetch(v0, v1), putOn(v1, v2), Rule(55).
buildWall(v0, v2) :- fetch(v0, v1), putOn(v1, v2), offset(v2), Rule(61).
buildWall(v1, v0) :- buildWall(v0, v1), invent_2(v2, v0), Rule(125).
invent_2(v1, v2) :- cont(v0), invent_2(v0, v1), buildWall(v1, v2), Rule(51).
invent_2(v0, v1) :- buildWall(v0, v1), invent_2(v1, v2), Rule(138).
invent_2(v2, v1) :- buildWall(v0, v1), invent_2(v2, v0), Rule(66).
invent_2(v2, v0) :- buildWall(v0, v1), invent_2(v1, v2), Rule(28).
invent_2(v0, v2) :- buildWall(v0, v1), invent_2(v2, v0), Rule(82).
buildWall(v2, v0) :- fetch(v0, v1), invent_2(v2, v0), Rule(73).
invent_2(v1, v0) :- buildWall(v0, v1), invent_2(v1, v2), Rule(12).
invent_2(v0, v2) :- buildWall(v0, v1), invent_2(v2, v1), Rule(152).
invent_2(v2, v1) :- buildWall(v0, v1), cont(v0), invent_2(v2, v0), Rule(5).
invent_2(v2, v1) :- buildWall(v0, v1), invent_2(v2, v0), offset(v1), Rule(60).
buildWall(v0, v1) :- invent_2(v0, v1), offset(v0), Rule(100).
buildWall(v0, v2) :- fetch(v0, v1), fetch(v2, v1), Rule(85).
invent_2(v1, v2) :- putOn(v0, v1), putOn(v0, v2), Rule(176).
buildWall(v2, v1) :- buildWall(v0, v1), offset(v0), buildWall(v2, v0), Rule(14).
buildWall(v2, v1) :- buildWall(v0, v1), cont(v1), invent_2(v2, v0), Rule(27).
invent_2(v2, v1) :- invent_2(v0, v1), invent_2(v1, v2), Rule(177).
invent_2(v2, v0) :- cont(v0), putOn(v1, v0), fetch(v2, v1), Rule(108).
buildWall(v1, v2) :- invent_2(v0, v1), invent_2(v2, v0), Rule(132).
buildWall(v0, v2) :- invent_2(v0, v1), invent_2(v1, v2), offset(v0), Rule(90).
invent_2(v2, v1) :- buildWall(v0, v1), invent_2(v0, v2), Rule(87).
invent_2(v0, v2) :- fetch(v0, v1), offset(v0), putOn(v1, v2), Rule(151).
invent_2(v0, v2) :- buildWall(v0, v1), buildWall(v1, v2), cont(v0), Rule(1).
invent_2(v2, v1) :- cont(v0), invent_2(v0, v1), buildWall(v2, v1), Rule(131).
invent_2(v2, v1) :- buildWall(v0, v1), cont(v0), buildWall(v2, v0), Rule(88).
buildWall(v0, v2) :- buildWall(v0, v1), buildWall(v2, v1), Rule(65).
invent_2(v2, v1) :- buildWall(v0, v1), buildWall(v2, v1), Rule(63).
invent_2(v1, v0) :- invent_2(v0, v1), putOn(v2, v0), Rule(76).
invent_2(v2, v1) :- buildWall(v0, v1), buildWall(v2, v0), Rule(0).
buildWall(v2, v1) :- buildWall(v0, v1), cont(v0), buildWall(v2, v0), Rule(16).
buildWall(v0, v2) :- buildWall(v0, v1), offset(v1), invent_2(v1, v2), Rule(112).
invent_2(v2, v1) :- invent_2(v0, v1), invent_2(v2, v0), Rule(37).
invent_2(v0, v2) :- buildWall(v0, v1), invent_2(v1, v2), offset(v2), Rule(156).
buildWall(v0, v2) :- invent_2(v0, v1), invent_2(v2, v1), Rule(113).
buildWall(v0, v2) :- buildWall(v0, v1), cont(v0), invent_2(v1, v2), Rule(34).
invent_2(v2, v0) :- buildWall(v0, v1), cont(v1), buildWall(v2, v0), Rule(155).
invent_2(v1, v0) :- buildWall(v0, v1), invent_2(v2, v0), Rule(33).
buildWall(v2, v0) :- buildWall(v0, v1), cont(v1), invent_2(v2, v0), Rule(150).
buildWall(v1, v2) :- buildWall(v0, v1), buildWall(v2, v0), Rule(157).
invent_2(v2, v0) :- cont(v0), invent_2(v1, v0), invent_2(v2, v1), Rule(116).
invent_2(v1, v2) :- buildWall(v0, v1), buildWall(v1, v2), Rule(174).
buildWall(v2, v0) :- fetch(v0, v1), putOn(v1, v2), Rule(147).
invent_2(v2, v1) :- buildWall(v0, v1), buildWall(v2, v0), cont(v1), Rule(58).
invent_2(v2, v1) :- buildWall(v0, v1), invent_2(v2, v0), cont(v2), Rule(8).
invent_2(v2, v1) :- buildWall(v0, v1), cont(v1), invent_2(v2, v0), Rule(48).
invent_2(v1, v2) :- buildWall(v0, v1), invent_2(v2, v0), Rule(13).
buildWall(v0, v1) :- invent_2(v0, v1), offset(v1), Rule(78).
invent_2(v0, v2) :- buildWall(v0, v1), buildWall(v2, v0), Rule(170).
buildWall(v0, v2) :- buildWall(v0, v1), cont(v1), invent_2(v1, v2), Rule(165).
buildWall(v2, v1) :- invent_2(v0, v1), offset(v0), invent_2(v2, v0), Rule(64).
buildWall(v1, v0) :- buildWall(v0, v1), putOn(v2, v0), Rule(79).
invent_2(v2, v1) :- buildWall(v0, v1), invent_2(v1, v2), Rule(158).
invent_2(v2, v0) :- buildWall(v0, v1), invent_2(v2, v1), Rule(32).
invent_2(v0, v2) :- buildWall(v0, v1), buildWall(v2, v1), Rule(105).
invent_2(v2, v0) :- invent_2(v0, v1), offset(v1), buildWall(v2, v0), Rule(115).
invent_2(v0, v2) :- buildWall(v0, v1), buildWall(v1, v2), offset(v0), Rule(74).
invent_2(v0, v1) :- buildWall(v0, v1), putOn(v2, v1), Rule(69).
buildWall(v0, v1) :- invent_2(v0, v1), putOn(v2, v0), Rule(3).
invent_2(v0, v1) :- buildWall(v0, v1), offset(v1), Rule(10).
buildWall(v0, v2) :- buildWall(v0, v1), invent_2(v2, v1), Rule(126).
invent_2(v1, v2) :- buildWall(v0, v1), buildWall(v0, v2), Rule(20).
invent_2(v0, v2) :- buildWall(v0, v1), invent_2(v1, v2), Rule(175).
invent_2(v0, v2) :- buildWall(v0, v1), cont(v1), buildWall(v0, v2), Rule(23).
buildWall(v1, v0) :- buildWall(v0, v1), invent_2(v1, v2), Rule(153).
buildWall(v2, v1) :- invent_2(v0, v1), invent_2(v2, v0), offset(v1), Rule(127).
buildWall(v0, v2) :- buildWall(v0, v1), buildWall(v1, v2), cont(v0), Rule(52).
buildWall(v2, v1) :- buildWall(v0, v1), cont(v0), invent_2(v2, v1), Rule(161).
buildWall(v0, v2) :- buildWall(v0, v1), invent_2(v2, v0), Rule(169).
buildWall(v1, v2) :- invent_2(v0, v1), invent_2(v1, v2), Rule(96).
buildWall(v2, v0) :- invent_2(v0, v1), invent_2(v2, v0), Rule(97).
buildWall(v2, v1) :- buildWall(v0, v1), invent_2(v2, v1), Rule(94).
invent_2(v0, v2) :- invent_2(v0, v1), invent_2(v2, v1), Rule(95).
buildWall(v2, v1) :- buildWall(v0, v1), buildWall(v1, v2), Rule(101).
invent_2(v1, v2) :- invent_2(v0, v1), invent_2(v0, v2), Rule(167).
buildWall(v2, v0) :- buildWall(v0, v1), invent_2(v1, v2), Rule(49).
buildWall(v2, v1) :- buildWall(v0, v1), invent_2(v2, v0), cont(v2), Rule(67).
buildWall(v0, v2) :- invent_2(v0, v1), offset(v1), invent_2(v0, v2), Rule(57).
buildWall(v0, v1) :- cont(v0), invent_2(v0, v1), Rule(47).
buildWall(v0, v2) :- fetch(v0, v1), offset(v0), putOn(v1, v2), Rule(86).
invent_2(v0, v2) :- buildWall(v0, v1), cont(v0), invent_2(v1, v2), Rule(68).
invent_2(v2, v1) :- cont(v0), invent_2(v1, v0), buildWall(v2, v1), Rule(109).
buildWall(v2, v1) :- cont(v0), invent_2(v0, v1), invent_2(v2, v0), Rule(26).
buildWall(v0, v2) :- buildWall(v0, v1), invent_2(v1, v2), offset(v0), Rule(98).
buildWall(v1, v2) :- invent_2(v0, v1), invent_2(v0, v2), Rule(81).
buildWall(v0, v2) :- buildWall(v0, v1), invent_2(v1, v2), Rule(2).
buildWall(v2, v1) :- buildWall(v0, v1), buildWall(v2, v0), offset(v1), Rule(31).
invent_2(v1, v2) :- buildWall(v0, v1), buildWall(v2, v0), Rule(168).
invent_2(v2, v1) :- buildWall(v0, v1), offset(v0), invent_2(v2, v0), Rule(93).
buildWall(v2, v0) :- buildWall(v0, v1), invent_2(v2, v1), Rule(164).
buildWall(v0, v1) :- invent_2(v0, v1), putOn(v2, v1), Rule(18).
invent_2(v1, v2) :- invent_2(v0, v1), invent_2(v2, v0), Rule(171).
invent_2(v0, v2) :- fetch(v0, v1), fetch(v2, v1), Rule(41).
buildWall(v2, v1) :- cont(v0), invent_2(v0, v1), invent_2(v2, v1), Rule(144).
buildWall(v2, v1) :- invent_2(v0, v1), offset(v0), invent_2(v2, v1), Rule(71).
buildWall(v1, v2) :- putOn(v0, v1), putOn(v0, v2), Rule(143).
invent_2(v2, v1) :- cont(v0), invent_2(v0, v1), invent_2(v2, v0), Rule(21).
buildWall(v2, v1) :- buildWall(v0, v1), invent_2(v0, v2), Rule(92).
buildWall(v2, v1) :- buildWall(v0, v1), buildWall(v2, v0), Rule(166).
invent_2(v2, v0) :- fetch(v0, v1), putOn(v1, v2), Rule(38).
buildWall(v2, v0) :- cont(v0), putOn(v1, v0), fetch(v2, v1), Rule(104).
buildWall(v1, v2) :- cont(v0), invent_2(v0, v1), invent_2(v1, v2), Rule(130).
invent_2(v0, v2) :- buildWall(v0, v1), invent_2(v1, v2), cont(v2), Rule(149).
buildWall(v1, v2) :- cont(v0), invent_2(v1, v0), invent_2(v1, v2), Rule(80).
invent_2(v1, v2) :- buildWall(v0, v1), cont(v0), buildWall(v1, v2), Rule(43).
invent_2(v2, v1) :- buildWall(v0, v1), invent_2(v2, v0), offset(v2), Rule(72).
buildWall(v2, v0) :- cont(v0), invent_2(v1, v0), invent_2(v2, v1), Rule(91).
buildWall(v2, v0) :- buildWall(v0, v1), offset(v1), invent_2(v2, v0), Rule(120).
buildWall(v0, v2) :- buildWall(v0, v1), cont(v1), invent_2(v0, v2), Rule(4).
